name: datagen
description: A Dart CLI tool for analyzer-based, extremely fast and clean data class code generation.
version: 1.0.0-beta1
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/datagen
keywords:
  - dart cli
  - dart tool
  - data class
  - copyWith
  - fromJson
  - toJson
  - lightweight
  - code generation
  - datagen
  - freezed free
  - build_runner free

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  analyzer: ^8.4.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
